general:
  project_name: 'BarcodeRecognizer'
  experiment_name: 'first_run'
  max_steps: 1300
  dotenv_path: '.env'

hardware:
  accelerator: 'gpu'
  precision: 32
  devices: [0, 1]

optimizer: 'torch.optim.AdamW'
optimizer_kwargs:
  lr: 1e-3
  weight_decay: 1e-5

scheduler: 'src.utils.schedulers.CosineAnnealingWarmup'
scheduler_kwargs:
  min_lr: 1e-5
  warmup_steps: 300
  decay_steps: 1000

callbacks:
  monitor_metric: 'val_string_match'
  monitor_mode: 'max'
  early_stopping_patience: 250
  progress_bar_refresh_rate: 1

model:
  encoder_name: "resnet18"
  num_classes: 11
  rnn_features_num: 48
  rnn_hidden_size: 128
  rnn_num_layers: 2

losses:
  -
    name: "CTCLoss"
    loss_weight: 1
    loss_fn: "torch.nn.CTCLoss"
    loss_kwargs:
      reduction: mean
      blank: 0
      zero_infinity: True

transforms_settings:
  preprocessing: True
  augmentations: True
  text_size: 13
  vocab: "0123456789"
  img_width: 416
  img_heigth: 96
  crop_persp_prob: 0.8
  scalex_prob: 0.8
  rbc_prob: 1
  clahe_prob: 0.5
  blur_limit: 3
  blur_prob: 0.3
  noise_prob: 0.3
  downscale_min: 0.3
  downscale_max: 0.7
  downscale_prob: 0.5
  max_holes: 10
  min_holes: 5
  coarse_prob: 0.3

base_data_settings:
  data_path: "data"
  train_size: 0.8
  batch_size: 106
  num_workers: 20
